# Generated by Django 5.0.3 on 2024-04-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_alter_diagnosis_options_alter_species_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('c', 'Chronic')], default='n', max_length=1),
        ),
    ]
