# Generated by Django 5.0.3 on 2024-04-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_alter_diagnosis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
