# Generated by Django 5.0.3 on 2024-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_alter_exhibit_name_alter_healthcondition_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['treatment_status'], 'verbose_name_plural': 'diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='status',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='treatment_status',
            field=models.CharField(choices=[(1, 'Treated'), (0, 'Untreated'), (-1, 'Chronic')], default=0, max_length=1),
        ),
    ]
