# Generated by Django 5.0.3 on 2024-04-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_alter_diagnosis_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='death_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='date',
            field=models.DateField(verbose_name='date diagnosed'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatment_status',
            field=models.CharField(choices=[('t', 'Treated'), ('u', 'Untreated'), ('c', 'Chronic')], default='u', max_length=1),
        ),
    ]
