# Generated by Django 5.0.3 on 2024-04-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_animal_death_date_alter_diagnosis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
