# Generated by Django 5.0.3 on 2024-04-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_alter_animal_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
