# Generated by Django 5.0.3 on 2024-04-12 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_alter_species_common_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingappointment',
            name='animals',
        ),
        migrations.AddField(
            model_name='feedingappointment',
            name='exhibit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.exhibit'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeedingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.feedingappointment')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
