# Generated by Django 5.0.3 on 2024-04-27 02:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_remove_feedingappointment_animals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingaction',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='feedingaction',
            name='time',
        ),
        migrations.AddField(
            model_name='feedingaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 21, 52, 49, 708481)),
        ),
        migrations.AddField(
            model_name='feedingaction',
            name='exhibit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.exhibit'),
            preserve_default=False,
        ),
    ]
