# Generated by Django 5.0.3 on 2024-05-03 21:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_remove_feedingaction_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='exhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo.exhibit'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.species'),
        ),
        migrations.AlterField(
            model_name='feedingaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 16, 20, 43, 927408)),
        ),
    ]
