# Generated by Django 5.0.4 on 2024-05-07 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0012_alter_feedingaction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 17, 41, 19, 886112)),
        ),
    ]
